version: "3.9"

services:
    deliverycx_backend:
        container_name: development_backend
        env_file:
            - ./server/.production.env
        depends_on:
            - redis
            - mongodb
        build:
            context: ./server
        networks:
          - mynetwork
        links:
            - redis
        volumes:
          - "./server/pinologs:/usr/node/app/pinologs"
    redis:
        image: redis
        command:
            - "redis-server"
            - "--loglevel ${REDIS_LOGLEVEL:-warning}"
            - "--databases 2"
            - "--save 900 1"
            - "--save 300 10"
            - "--save 60 10000"
        volumes:
            - ./redis/data:/data
        networks:
          - mynetwork
    mongodb:
        container_name: development_mongodb
        image: mongo
        volumes:
            - ./mongo/data:/data/db    
        ports:
          - "27017:27017"
        networks:
            - mynetwork
networks:
  mynetwork:
    external:
      name: delivglobalnetwork             