version: "3.9"

services:
  deliverycx_backend:
    container_name: development_backend
    env_file:
      - ./server/.development.local.env
    depends_on:
      - redis
      - mongodb
      - rabbitmq
    build:
      context: ./server
    ports:
          - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379  
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27012
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672  
    networks:
      - my_global_network

  redis:
    image: redis
    command:
      - "redis-server"
      - "--loglevel ${REDIS_LOGLEVEL:-warning}"
      - "--databases 2"
      - "--save 900 1"
      - "--save 300 10"
      - "--save 60 10000"
    ports:
      - "6379:6379"
    networks:
      - my_global_network

  mongodb:
    container_name: development_mongodb
    image: mongo
    volumes:
      - ./mongo/data:/data/db    
    expose:
      - 27017
    ports:
      - "27012:27017"
    networks:
      - my_global_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672"
    networks:
      - my_global_network

networks:
  my_global_network:
    driver: bridge
    external: true