FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./


RUN npm install -g npm@latest 

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 5000

RUN npm install -g @nestjs/cli nodemon

CMD ["npm", "run", "start:dev"]